### ISSUE TITLE
被禁用的监控主机

### ISSUE THREAD

**Issue by hklinux2010** [canghai908/zbxtable#102]
提个意见：

被禁用的监控主机就不要展示在页面上面了
!
![2%~)8 %1ZN(8Q~{S9 ZS@@2](https://github.com/canghai908/zbxtable/assets/72911366/4c02585c-eda3-474b-8957-c31d8acc2784)

不太好看

**Comment by canghai908** [comment]
想法不错，可以配置成默认不加载，可以自己配置加载，下个版本实现。

**Comment by canghai908** [comment]
2.1.6已配置禁用主机不显示
