### ISSUE TITLE
linux设备硬盘存储空间空间使用率未能获取问题

### ISSUE THREAD

**Issue by laopiqiu** [canghai908/zbxtable#104]
大佬您好，我部署的zabbix 版本是6.4.8部署在docker里，zbxtable版本是2.1.5部署在docker外。现在数据映射已经做好了，但是硬盘数据是没有的。测试监控的设备是zabbix服务器本身，使用的是自带的linux by zabbix agent模板
![zbxtable硬盘数据为空](https://github.com/canghai908/zbxtable/assets/161403545/3890d1c7-acdf-47e8-befb-5585f9b647ef)

**Comment by canghai908** [comment]
zabbix6.4版本和即将要出来的7模板有变化，等7.0发布后再一起处理。
