### ISSUE TITLE
systemd服务开机启动会失败

### ISSUE THREAD

**Issue by fcwys** [canghai908/zbxtable#108]
使用services注册服务，手动执行systemctl start zbxtable.service正常，systemctl enable zbxtable.service加入开机启动项，重启机器后自动启动失败，查看日志似乎是mysql还未启动完成导致数据库连接失败，希望能改进服务注册和启动依赖判断，谢谢！

**Comment by Hi-360** [comment]
这问题存在好久了 每次我都是手动

**Comment by canghai908** [comment]
systemd启动文件添加
```
After=network.target
After=mysql.service
After=mysqld.service
After=mariadb.service
After=postgresql.service
```
即可
