### ISSUE TITLE
更新2.16后，zbxtable服务无法启动，大概是什么问题？

### ISSUE THREAD

**Issue by himz1991** [canghai908/zbxtable#114]
更新2.16后，zbxtable服务无法启动，大概是什么问题？

求大神老张解答

[root@zbxtable conf]# systemctl status zbxtable
● zbxtable.service - zbxtable
   Loaded: loaded (/etc/systemd/system/zbxtable.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2024-09-23 09:16:22 CST; 2s ago
  Process: 2360 ExecStart=/bin/bash -c /usr/local/zbxtable/zbxtable web (code=exited, status=1/FAILURE)
 Main PID: 2360 (code=exited, status=1/FAILURE)

Sep 23 09:16:21 zbxtable bash[2360]: table `zbxtable_user_group` already exists, skip
Sep 23 09:16:21 zbxtable bash[2360]: table `zbxtable_event_log` already exists, skip
Sep 23 09:16:21 zbxtable bash[2360]: [ORM]2024/09/23 09:16:21  -[Queries/default] - [  OK / db.QueryRow /     ...admin`
Sep 23 09:16:21 zbxtable bash[2360]: [ORM]2024/09/23 09:16:21  -[Queries/default] - [  OK /    db.Query /     0.2ms]...
Sep 23 09:16:21 zbxtable bash[2360]: [ORM]2024/09/23 09:16:21  -[Queries/default] - [  OK /    db.Query /     ...` T0 ]
Sep 23 09:16:21 zbxtable bash[2360]: [ORM]2024/09/23 09:16:21  -[Queries/default] - [  OK /    db.Query /     0.2ms]...
Sep 23 09:16:22 zbxtable bash[2360]: 2024/09/23 09:16:22.123 [I] [web.go:60]  Zabbix API connected！Zabbix ver…n: 6.0.0
Sep 23 09:16:22 zbxtable systemd[1]: zbxtable.service: main process exited, code=exited, status=1/FAILURE
Sep 23 09:16:22 zbxtable systemd[1]: Unit zbxtable.service entered failed state.
Sep 23 09:16:22 zbxtable systemd[1]: zbxtable.service failed.
Hint: Some lines were ellipsized, use -l to show in full

**Comment by canghai908** [comment]
新版本需要模拟登录，因此配置文件中的zabbix_pass必须配置。

**Comment by himz1991** [comment]
之前已经配置了的，哪个文件还需要配置？

; zbxtable
appname         = zbxtable
httpport        = 8085
runmode         = dev
timeout         = 12
token           = de0c0d234f054c74b3d87d715f69afb6
copyrequestbody = true
EnableDocs      = true

; log
log_level       = 6
log_path        = logs/app.log
maxlines        = 1000
maxsize         = 0
maxdays         = 10
daily           = true

; database
dbtype          = mysql
dbhost          = 127.0.0.1
dbuser          = zbxtable
dbpass          = zbxtablepwd123
dbname          = zbxtable
dbport          = 3306

;redis
redis_host      = 127.0.0.1
redis_port      = 6379
redis_pass      =
redis_db        = 8

; zabbix
zabbix_web      = http://192.168.101.111/api_jsonrpc.php
zabbix_user     = Admin
zabbix_pass     = mds123456
zabbix_token    =

; mail
email_from       = xxx@qq.com
email_port       = 465
email_host       = smtp.qq.com

**Comment by canghai908** [comment]
zabbix_web 配置错误，不需要加api_jsonrpc.php，直接配置zabbix_web = http://192.168.101.111 即可

**Comment by himz1991** [comment]
好了，谢谢老张大神，但是我之前一直加上api_jsonrpc.php才可以正常使用
