### ISSUE TITLE
流量报表好像遇到一个bug

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#116]
![image](https://github.com/user-attachments/assets/19cd6de9-ad55-46a6-bbf9-60c28344c273)
![image](https://github.com/user-attachments/assets/e8a3a7e0-ca5e-4ae7-ad2b-bd7bed587373)

你好 流量报表好像遇到一个bug，我这边是上下行100Mbps的专线   后面这边不应该是mbps嘛？这个上面是“MB”

**Comment by canghai908** [comment]
已修复
