### ISSUE TITLE
MS-Agent 怎么卸载，安装过一次，再次用不同的服务器部署环境都提示已经存在

### ISSUE THREAD

**Issue by roadpersonal** [canghai908/zbxtable#117]
[command.go:273]  -32602 (Invalid params.): Media type "MS-Agent Media" already exists.

**Comment by canghai908** [comment]
使用
```
./zbxtable uninstall
```
卸载！或者手动清理MS-Agent相关告警媒介、用户、用户组、动作即可。

**Comment by roadpersonal** [comment]
对于zabbix 部署 是HA 的环境，ms-agent 安装在哪一台zabbix server上，还是都要安装

**Comment by canghai908** [comment]
都要部署
