### ISSUE TITLE
zbxtable 是不支持自定义的zabbix web登录吗， zabbix登录界面有自定义logo和图片，似乎就不太行

### ISSUE THREAD

**Issue by roadpersonal** [canghai908/zbxtable#119]
2024/11/05 16:07:44.549 [I] [web.go:60]  Zabbix API connected！Zabbix version: 7.0.0
2024/11/05 16:07:44.824 [I] [base.go:171]  Login to zabbix response body is: <!DOCTYPE html><html lang="en" theme="blue-theme" color-scheme="light">    <head>
                <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta name="Author" content="Zabbix SIA" /><title>CD-Zabbix Server: Zabbix</title>              <link rel="icon" href="favicon.ico">
                <link rel="apple-touch-icon-precomposed" sizes="76x76" href="assets/img/apple-touch-icon-76x76-precomposed.png">
                <link rel="apple-touch-icon-precomposed" sizes="120x120" href="assets/img/apple-touch-icon-120x120-precomposed.png">
                <link rel="apple-touch-icon-precomposed" sizes="152x152" href="assets/img/apple-touch-icon-152x152-precomposed.png">
                <link rel="apple-touch-icon-precomposed" sizes="180x180" href="assets/img/apple-touch-icon-180x180-precomposed.png">
                <link rel="icon" sizes="192x192" href="assets/img/touch-icon-192x192.png">
                <meta name="msapplication-TileImage" content="assets/img/ms-tile-144x144.png">
                <meta name="msapplication-TileColor" content="#d40000">
                <meta name="msapplication-config" content="none"/><link rel="stylesheet" type="text/css" href="assets/styles/blue-theme.css?1722501773"><style>:root {
--severity-color-na-bg: #97AAB3;
--severity-color-info-bg: #7499FF;
--severity-color-warning-bg: #FFC859;
--severity-color-average-bg: #FFA059;
--severity-color-high-bg: #E97659;
--severity-color-disaster-bg: #E45959;
}
.na-bg, .na-bg input[type="radio"]:checked + label, .na-bg:before, .flh-na-bg, .status-na-bg, .status-na-bg:before { background-color: #97AAB3 }
.info-bg, .info-bg input[type="radio"]:checked + label, .info-bg:before, .flh-info-bg, .status-info-bg, .status-info-bg:before { background-color: #7499FF }
.warning-bg, .warning-bg input[type="radio"]:checked + label, .warning-bg:before, .flh-warning-bg, .status-warning-bg, .status-warning-bg:before { background-color: #FFC859 }
.average-bg, .average-bg input[type="radio"]:checked + label, .average-bg:before, .flh-average-bg, .status-average-bg, .status-average-bg:before { background-color: #FFA059 }
.high-bg, .high-bg input[type="radio"]:checked + label, .high-bg:before, .flh-high-bg, .status-high-bg, .status-high-bg:before { background-color: #E97659 }
.disaster-bg, .disaster-bg input[type="radio"]:checked + label, .disaster-bg:before, .flh-disaster-bg, .status-disaster-bg, .status-disaster-bg:before { background-color: #E45959 }

</style><script>
                        const PHP_ZBX_FULL_DATE_TIME = "Y-m-d h:i:s A";
                        const PHP_TZ_OFFSETS = [0];
                </script><script src="js/browsers.js?1716964533"></script></head>
<body><div class="wrapper"><div style="position: absolute;height: 100%;width: 100%;background: url(/zabbix/logo/logo.jpg)no-repeat 0 0;background-size:100% 100%;"></div><main><div class="server-name">CD-Zabbix Server</div><div class="signin-container"><div class="signin-logo"><div class="zabbix-logo"></div></div><form method="post" action="index.php" accept-charset="utf-8" aria-label="Sign in"><ul><li><label for="name">Username</label><input type="text" id="name" name="name" value="" maxlength="255" autofocus="autofocus"><div class="red">Incorrect user name or password or account is temporarily blocked.</div></li><li><label for="password">Password</label><input type="password" id="password" name="password" value="" maxlength="255" autocomplete="off"></li><li><input type="checkbox" id="autologin" name="autologin" value="1" class="checkbox-radio" checked="checked"><label for="autologin" title="Remember me for 30 days"><span></span>Remember me for 30 days</label></li><li><button type="submit" id="enter" name="enter" value="Sign in">Sign in</button></li></ul></form></div><div class="signin-links"><a target="_blank" rel="noopener noreferrer" class="grey link-alt" href="https://www.zabbix.com/documentation/7.0/">Help</a>&nbsp;&nbsp;&bullet;&nbsp;&nbsp;<a target="_blank" rel="noopener noreferrer" class="grey link-alt" href="https://www.zabbix.com/support">Support</a></div></main><footer role="contentinfo">&copy; 2001&ndash;2024, <a class="grey link-alt" target="_blank" rel="noopener noreferrer" href="https://www.zabbix.com/">Zabbix SIA</a></footer></div></body>

2024/11/05 16:07:44.825 [E] [base.go:171]  Login to Zabbix failed!

**Comment by roadpersonal** [comment]
用api 不行， 用账号密码又行了

**Comment by canghai908** [comment]
看返回时是zabibx密码错误，7.0版本api用的token登录的没检查下zabbix登录的账号密码
