### ISSUE TITLE
问题数显示不准确及页面参数刷新后失效

### ISSUE THREAD

**Issue by maizi33** [canghai908/zbxtable#12]
![屏幕截图 2020-12-07 103529](https://user-images.githubusercontent.com/41134848/101303010-07060c80-3878-11eb-95fc-e146433a672c.png)

右上角问题数与中间的”全部“”警告“”一般“数字不吻合，另外，设置刷新时间和每页条数，刷新浏览器界面后又回到了默认值。
本地部署和官网demo都存在这个问题

**Comment by canghai908** [comment]
1.首页问题统计里包含禁用主机的问题数，下面问题为为恢复告警，不包含禁用主机，升级zbxtable 1.1.0版本解决。
2.刷新问题已修复，升级zbxtable web 1.0.5到最新版本即可。
