### ISSUE TITLE
数据初始化问题，计算机组初始错误，一个计算机组含有Windows计算机和Linux计算机，现在初始化到了Windows计算机，现在把这个组换了纯Windows的计算机组初始化，原先的Linux主机还在Windows里，这个怎么删除

### ISSUE THREAD

**Issue by roadpersonal** [canghai908/zbxtable#120]

**Comment by canghai908** [comment]
主机字段里，删除type类型，
<img width="631" alt="image" src="https://github.com/user-attachments/assets/cd621c38-1e78-4f45-88a4-8424e6ac17e2">
