### ISSUE TITLE
Zbxtable2.1.7 数据面板为空

### ISSUE THREAD

**Issue by Lin-shuaibi** [canghai908/zbxtable#123]
升级Zbxtable2.1.7后 打开了zabbix数据面板功能 但是数据一直是空的。
Zabbix版本 | 5.0.45
Zbxtable前端版本
![zabbix](https://github.com/user-attachments/assets/53c58075-236e-471e-9cd9-9e4b953a02d0)
![zbx数据面板](https://github.com/user-attachments/assets/0095e4db-d63f-4ba0-86f3-267288691aa2)
![版本信息](https://github.com/user-attachments/assets/e4e794a3-0c38-41e8-9a51-2e107d030d65)

：2.1.7
后端版本Version: 2.1.7
GitHash:8be653c218a48281f376236ace33ee6d51da9199
BuildTime:2024-12-23_12:28:02PM

**Comment by canghai908** [comment]
需要独立配置，配置教程https://zbxtable.com/docs/usage/dashboard/
