### ISSUE TITLE
数据面板提示nginx错误

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#124]
张总按照你的教程进行配置了  但是出现问题了    
![image](https://github.com/user-attachments/assets/3392a623-3ad7-4dcb-9fe1-6b71a1a25c86)
![image](https://github.com/user-attachments/assets/0e02b586-2db5-4260-83b3-afb2ff1d3937)

错误日志我放在附件当中了 
[error.log](https://github.com/user-attachments/files/18250182/error.log)

**Comment by canghai908** [comment]
zbxtable服务器上
```
curl -l http://172.31.6.7:8080/
```
 看下把，看日志是不通

**Comment by Hi-360** [comment]
![image](https://github.com/user-attachments/assets/36e947be-6e40-49b0-ba15-1272c9af8450)
提示拒绝连接

**Comment by canghai908** [comment]
不通你玩啥呢，这机器要能访问zabbix平台pass地址你的zabbix地址

**Comment by Hi-360** [comment]
感谢 马虎了


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月26日 14:46 |
| 收件人 | ***@***.***> |
| 抄送人 | Wu ***@***.***>,
***@***.***> |
| 主题 | Re: [canghai908/zbxtable] 数据面板提示nginx错误 (Issue #124) |

zbxtable服务器上 curl -l http://172.31.6.7:8080/ 看下把，看日志是不通
