### ISSUE TITLE
选择框没自适应导致无法看到具体信息

### ISSUE THREAD

**Issue by 692568516** [canghai908/zbxtable#14]
当前位置：    指标报表    指标导出这里，主机组，主机下拉框比较小，无法显示完整信息，当主机比较多的时候就需要一个一个点才知道是那个主机，另外建议增加导出功能导出的是一段时间内的最大  最小，平均，95 值

**Comment by canghai908** [comment]
多谢建议，1.1.2版本前端界面所有选择框已添加tips标，请尽快更新。
![image](https://user-images.githubusercontent.com/1450994/110054813-c47c9f00-7d96-11eb-945f-f052c0e711f5.png)
导出数据来自zabbix数据库，选择导出趋势数据即可导出一小时内的最大 最小，平均，95目前在数据库没有存储，因此无法导出，需要自行计算。
