### ISSUE TITLE
register db Ping `default`, Error 1045: Access denied for user 'zbxtable'@'localhost' 

### ISSUE THREAD

**Issue by gzm223518** [canghai908/zbxtable#16]
![QQ图片20210308164708](https://user-images.githubusercontent.com/53427034/110297279-44706680-802e-11eb-856c-def5f5f86ce3.png)
您好，这个是什么问题 我已经给了用户所有权限，但是服务还是无法启动成功

**Comment by canghai908** [comment]
使用
```
./zbxtable init
```
初始化了配置文件吗？连接是否ok？

**Comment by gzm223518** [comment]
> 使用
> 
> ```
> ./zbxtable init
> ```
> 
> 初始化了配置文件吗？连接是否确定？

初始化过了，而且登陆页面也是可以打开的 但是输入账号密码后会有报错
![9946F2E8-FCBD-4fec-9098-85D895B4C2DB](https://user-images.githubusercontent.com/53427034/110301368-f6aa2d00-8032-11eb-884d-28ed621e0ac2.png)

**Comment by canghai908** [comment]
这个是后台没有启动，日志显示数据库连接错误，检查下配置文件里的数据库连接信息，是否ok，另外zbxtable版本是什么。

**Comment by gzm223518** [comment]
> 这个是后台没有启动，日志显示数据库连接错误，检查下配置文件里的数据库连接信息，是否ok，另外zbxtable版本是什么。

好的 我再试下 版本是1.1.2的 非常感谢

**Comment by canghai908** [comment]
@gzm223518 升级一下刚发布的1.1.3版本，这个1.1.2版本init脚本有个bug，升级文档：https://zbxtable.cactifans.com/releases/zbxtable-1.1.3.html
