### ISSUE TITLE
在图形管理界面，图形无法显示

### ISSUE THREAD

**Issue by SagerPing** [canghai908/zbxtable#19]
用浏览器点开一台服务器查看图形时图片裂开无法显示。
查看日志会出现错误信息 Handler crashed with error can't find templatefile in the path:views/imagescontroller/getone.tpl

**Comment by canghai908** [comment]
配置文件里，zabbix地址最后不能以 / 结尾，直接写地址比如:http://192.168.0.1.1 即可，不能带 结尾的 /
