### ISSUE TITLE
zbxtable 无法启动| zbxtable 脚本报错

### ISSUE THREAD

**Issue by smile718** [canghai908/zbxtable#2]
[root@localhost zbxtable]# systemctl status zbxtable
● zbxtable.service - zbxtable
   Loaded: loaded (/usr/lib/systemd/system/zbxtable.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 二 2020-08-11 10:26:15 CST; 5s ago
  Process: 2472 ExecStart=/bin/bash -c /usr/local/zbxtable/zbxtable web (code=exited, status=2)
 Main PID: 2472 (code=exited, status=2)

8月 11 10:26:15 localhost.localdomain systemd[1]: Started zbxtable.
8月 11 10:26:15 localhost.localdomain bash[2472]: table `zbxtable_alarm` already exists, skip
8月 11 10:26:15 localhost.localdomain bash[2472]: table `zbxtable_manager` already exists, skip
8月 11 10:26:15 localhost.localdomain bash[2472]: [ORM]2020/08/11 10:26:15  -[Queries/default] - [  OK / db.QueryRow /     0.3ms] - [SELECT `id`, `username`, `passwo... - `admin`
8月 11 10:26:15 localhost.localdomain bash[2472]: **panic: interface conversion: interface {} is nil, not string**
8月 11 10:26:15 localhost.localdomain systemd[1]: zbxtable.service: main process exited, code=exited, status=2/INVALIDARGUMENT
8月 11 10:26:15 localhost.localdomain systemd[1]: Unit zbxtable.service entered failed state.
8月 11 10:26:15 localhost.localdomain systemd[1]: zbxtable.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

----------------------------------------------------------------------------------------------------------------------------------------
[root@localhost zbxtable]# ./zbxtable install
2020/08/11 10:25:40.079 [I] [install.go:44]  Zabbix API Address: https://monitor.cokutau.cn/api_jsonrpc.php 
2020/08/11 10:25:40.079 [I] [install.go:45]  Zabbix Admin User: xxxxxxxxxx 
2020/08/11 10:25:40.079 [I] [install.go:46]  Zabbix Admin Password: xxxxxxxxxx
**panic: interface conversion: interface {} is nil, not string**

goroutine 1 [running]:
github.com/canghai908/zabbix-go.(*API).Login(0xc0000853e0, 0xc000034f40, 0xc, 0xc000034f60, 0x9, 0xc000038330, 0x2a, 0x4f4a98, 0x68)
	/home/mygo/pkg/mod/github.com/canghai908/zabbix-go@v0.0.0-20190301064811-5577c772412c/base.go:141 +0x2b3
github.com/canghai908/zbxtable/cmd.installAagent(0xc0002de840)
	/var/lib/jenkins/workspace/zbxtable-rpm-centos7/cmd/install.go:48 +0x331
github.com/urfave/cli.HandleAction(0xcfa6a0, 0xec1520, 0xc0002de840, 0xc0002de840, 0x0)
	/home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:528 +0x7c
github.com/urfave/cli.Command.Run(0xe76f44, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe988e3, 0x27, 0x0, ...)
	/home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x57a
github.com/urfave/cli.(*App).Run(0xc0000e3880, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x7c7
main.main()
	/var/lib/jenkins/workspace/zbxtable-rpm-centos7/zbxtable.go:39 +0x16a

----------------------------------------------------------------------------------------------------------------------------------------------
#zbxtable 
appname = zbxtable
httpport = 8084
#runmode = prod
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

#session过期时间，单位为小时，默认12小时。如需大屏自动刷新，建议配置较大配置时间
session_timeout = 24

#database
hostname = localhost
username = zbxtable
dbpsword = Zabbixtable@123!
database = zbxtable
port = 3306
dbprefix = zbxtable_

#zabbix web info
zabbix_server = https://xxxxxxxxxx
zabbix_user = xxxxxxxxxx
zabbix_pass = xxxxxxxxxx

#alarm send token
token = ec573cf7388da56916f75ba9bbe46a69

**Comment by smile718** [comment]
蟹蟹大神，zabbix server的域名弄错了

**Comment by canghai908** [comment]
zabbix server地址为能访问zabbix server的地址 ，如后面有/zabbix，也必须携带。
