### ISSUE TITLE
zbxtable无法启动

### ISSUE THREAD

**Issue by s635157034** [canghai908/zbxtable#20]
日志提示信息：
6月 03 19:15:33 localhost.localdomain polkitd[1041]: Unregistered Authentication Agent for unix-process:128472:128796 (system bus name :1.42, object path /org/freedesktop/PolicyKit1/AuthenticationAgent
6月 03 19:15:33 localhost.localdomain bash[128479]: 2021/06/03 19:15:33.974 [I] [command.go:163]
6月 03 19:15:33 localhost.localdomain bash[128479]: $$$$$$$$\ $$$$$$$\  $$\   $$\ $$$$$$$$\  $$$$$$\  $$$$$$$\  $$\       $$$$$$$$\
6月 03 19:15:33 localhost.localdomain bash[128479]: \____$$  |$$  __$$\ $$ |  $$ |\__$$  __|$$  __$$\ $$  __$$\ $$ |      $$  _____|
6月 03 19:15:33 localhost.localdomain bash[128479]: $$  / $$ |  $$ |\$$\ $$  |   $$ |   $$ /  $$ |$$ |  $$ |$$ |      $$ |
6月 03 19:15:33 localhost.localdomain bash[128479]: $$  /  $$$$$$$\ | \$$$$  /    $$ |   $$$$$$$$ |$$$$$$$\ |$$ |      $$$$$\
6月 03 19:15:33 localhost.localdomain bash[128479]: $$  /   $$  __$$\  $$  $$<     $$ |   $$  __$$ |$$  __$$\ $$ |      $$  __|
6月 03 19:15:33 localhost.localdomain bash[128479]: $$  /    $$ |  $$ |$$  /\$$\    $$ |   $$ |  $$ |$$ |  $$ |$$ |      $$ |
6月 03 19:15:33 localhost.localdomain bash[128479]: $$$$$$$$\ $$$$$$$  |$$ /  $$ |   $$ |   $$ |  $$ |$$$$$$$  |$$$$$$$$\ $$$$$$$$\
6月 03 19:15:33 localhost.localdomain bash[128479]: \________|\_______/ \__|  \__|   \__|   \__|  \__|\_______/ \________|\________|
6月 03 19:15:33 localhost.localdomain bash[128479]: 2021/06/03 19:15:33.979 [I] [web.go:47]  Connected to database zbxtable successfully!
6月 03 19:15:34 localhost.localdomain bash[128479]: 2021/06/03 19:15:34.092 [I] [web.go:47]  Connected to zabbix web successfully！Zabbix version is : 5.2.5
6月 03 19:15:34 localhost.localdomain bash[128479]: table `zbxtable_alarm` already exists, skip
6月 03 19:15:34 localhost.localdomain bash[128479]: table `zbxtable_manager` already exists, skip
6月 03 19:15:34 localhost.localdomain bash[128479]: 2021/06/03 19:15:34.323 [E] [base.go:78]  Login to Zabbix failed!
6月 03 19:15:34 localhost.localdomain systemd[1]: zbxtable.service: main process exited, code=exited, status=1/FAILURE
6月 03 19:15:34 localhost.localdomain systemd[1]: Unit zbxtable.service entered failed state.
6月 03 19:15:34 localhost.localdomain systemd[1]: zbxtable.service failed.

原先部署成功过一次，因为太久没用忘记密码，数据库密码也忘了。就重新部署了，结果几次都是这么提示，账号密码都没错。

**Comment by canghai908** [comment]
看这个错误是zabbix登录失败，确保zabbix登录后首页是Dashboard页面。
