### ISSUE TITLE
在线看图表 ，图形管理 刷新不出来

### ISSUE THREAD

**Issue by srebro-cn** [canghai908/zbxtable#27]
![image](https://user-images.githubusercontent.com/53123002/131271538-350a9fd4-64cf-49f3-952f-ebd3e645bd4b.png)

**Comment by rollby** [comment]
我之前也疑惑这个问题很久，后来才发现是要点击主机名称才会出现图形。https://zbxtable.cactifans.com/docs/usage/graphtree/

**Comment by srebro-cn** [comment]
很奇怪 还是显示不出来，点击查询




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "canghai908/zbxtable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [canghai908/zbxtable] 在线看图表 ，图形管理 刷新不出来 (#27)





 
我之前也疑惑这个问题很久，后来才发现是要点击主机名称才会出现图形。https://zbxtable.cactifans.com/docs/usage/graphtree/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by srebro-cn** [comment]
您好，现在可以了 是点击主机名&nbsp; 就出现了


谢谢









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "canghai908/zbxtable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [canghai908/zbxtable] 在线看图表 ，图形管理 刷新不出来 (#27)





 
我之前也疑惑这个问题很久，后来才发现是要点击主机名称才会出现图形。https://zbxtable.cactifans.com/docs/usage/graphtree/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by canghai908** [comment]
点击查看图形
