### ISSUE TITLE
报表无法导出

### ISSUE THREAD

**Issue by gucci** [canghai908/zbxtable#3]
使用rpm包安装的最新版zbxtable，资源管理-》图形管理里面，点击导出按钮，一直在转圈，无法导出数据

**Comment by canghai908** [comment]
图形过多导出时间较长，可以选择图形少的主机尝试下看是否有问题

**Comment by gucci** [comment]
我是导出的zabbix-server的报表，8vCPU/16G的阿里云虚拟机，等了半小时都没有导出，有没有查日志的方法？

**Comment by canghai908** [comment]
@gucci 这个是很简单的逻辑，就是抓取图形，输出到pdf，看看zabbix web的http日志吧，是不是请求了。

**Comment by canghai908** [comment]
@gucci 更新了下导出的方法，更新到最新的1.0.5试试，应该就可以了。https://zbxtable.cactifans.com/releases/zbxtable-1.0.5.html

**Comment by gucci** [comment]
报表导出问题解决了，通常报表是定时任务的，您能开发一个定时任务的配置吗？

**Comment by canghai908** [comment]
@gucci 后续考虑中。
