### ISSUE TITLE
连接zabbix3.4 ，图形只能刷最近1h，导出PDF也是。

### ISSUE THREAD

**Issue by haining-zhn** [canghai908/zbxtable#30]
![QQ截图20210917132148](https://user-images.githubusercontent.com/70742886/133730174-b90b5f1d-2ba5-4f1e-8378-995efb46a858.png)

**Comment by haining-zhn** [comment]
![QQ截图20210917132148](https://user-images.githubusercontent.com/70742886/133730128-09ff57ae-95e0-4abb-bc8b-b510a3257a29.png)

**Comment by canghai908** [comment]
升级zbxtable到最新的版本试试

**Comment by haining-zhn** [comment]
> 
> 
> 升级zbxtable到最新的版本试试
还是不行。。。。

**Comment by canghai908** [comment]
老版本已经不在更新了 建议试下2.1
