### ISSUE TITLE
首页无法获取统计数据

### ISSUE THREAD

**Issue by zsy1986** [canghai908/zbxtable#31]
详细错误提示如下 
2021/09/28 08:29:05.556 [E] [tgrigger.go:28]  Post "http://192.168.3.72:8080/api_jsonrpc.php": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

请问有什么办法解决？

**Comment by zsy1986** [comment]
![Uploading 微信图片_20210928091431.png…]()

**Comment by canghai908** [comment]
很显然啊，连接zabbix失败，使用init 命令初始化配置文件

**Comment by zsy1986** [comment]
好像不是连不上zabbix的原因, 其他的功能是正常的。如下



***@***.***
 
发件人： sole
发送时间： 2021-10-09 22:42
收件人： canghai908/zbxtable
抄送： zsy1986; Author
主题： Re: [canghai908/zbxtable] 首页无法获取统计数据 (#31)
很显然啊，连接zabbix失败，使用init 命令初始化配置文件
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by canghai908** [comment]
检查zabbix地址
