### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'color')

### ISSUE THREAD

**Issue by everaldoscabral** [canghai908/zbxtable#33]
**Error:**

![image](https://user-images.githubusercontent.com/53796085/138005215-5442a924-5621-4a55-9ba8-c68cda2cf4c9.png)

**Version Zbxtable:**

![image](https://user-images.githubusercontent.com/53796085/138005330-dd99ba8a-3d8b-45ee-91fc-f0868bf8dbfc.png)

**Version Zabbix:**

5.4.6

**Comment by canghai908** [comment]
can try use zbxtable 2.0
