### ISSUE TITLE
zbxtable告警分析页面告警等级显示问题

### ISSUE THREAD

**Issue by linus-qintian** [canghai908/zbxtable#39]
您好，我安装的zabbix版本是5.0.22，zbxtable安装成功之后其他显示正常，告警分析页面如图，没有显示告警的等级（通知，告警等），显示的1，2，3，我想问一下这个是我安装的zbxtable的版本不对吗？还是设置有错误：
![Snipaste_2022-06-01_15-30-18](https://user-images.githubusercontent.com/65064941/171352368-ffd713d4-8b52-491b-b416-a64d5ff567db.png)
我看官方示例图片上是正常的https://blog.cactifans.com/2020/07/19/ZbxTable%E6%AD%A3%E5%BC%8F%E5%BC%80%E6%BA%90/
![482304D1-FD67-4C09-B6E5-7D0660D69556](https://user-images.githubusercontent.com/65064941/171353998-b307e0e9-aba8-4d7b-81ff-3425233c0d86.png)

**Comment by canghai908** [comment]
找个是软件问题，等几天更新版本就可以了

**Comment by linus-qintian** [comment]
老师您好，我还有一个问题就是我想把语言切成英语的时候其他的地方都会变化，但是告警页面的告警统计和告警TOP10不会跟随语言变化，一直是中文，请问这个也是软件的问题吗？谢谢老师
![Snipaste_2022-06-02_11-08-31](https://user-images.githubusercontent.com/65064941/171544719-681bedc6-a61e-42a7-9d41-49114bda8820.png)

**Comment by canghai908** [comment]
2.0版本更新了，可以尝试下2.0版本
