### ISSUE TITLE
2.0.1 功能很棒

### ISSUE THREAD

**Issue by macaty** [canghai908/zbxtable#42]
1、系统能实现自动采集服务器/网络资产CMDB（cpu数量、内存大小、磁盘大小、网卡速度、SN号码、MAC地址等）功能，好像有了基础功能，需要对接zabbix的采集模板和显示即可
2、实现top10功能，比如cpu/mem/disk/interface等

**Comment by canghai908** [comment]
2.1.0已发布，新功能正在开发，多谢支持
