### ISSUE TITLE
ms-agent安装成功，日志显示收到zabbix告警，但是前端界面不显示

### ISSUE THREAD

**Issue by linus-qintian** [canghai908/zbxtable#44]
您好，我在使用过程中遇到一些问题，试过了很多方法也花了很长时间还是没解决，想请您提供一点儿建议。
首先是我按照您提供的安装文档，安装ms-agent全程没有报错，zbxtable和ms-agent的token配置的也是一致的，在zabbix中测试ms-agent的媒介类型是成功的。 
![Snipaste_2022-07-28_21-57-21](https://user-images.githubusercontent.com/65064941/181524425-eb11e77a-f5fe-4dac-8927-7a3a2e33df34.png)
但是当zabbix产生问题告警时ms-agent会提示"No message defined for media type."
![Snipaste_2022-07-28_22-15-27](https://user-images.githubusercontent.com/65064941/181531426-4e33673f-8b9c-431d-a5f1-136a7d059bb6.png)
上网查询是因为没有配置报警媒介类型中的Message templates
![Snipaste_2022-07-28_22-02-56](https://user-images.githubusercontent.com/65064941/181529629-d4041c22-fb6d-4ca3-80df-93cd1eddc24d.png)
配置完后这个问题解决，zabbix显示将告警发送给了zbxtable，我将/usr/lib/zabbix/alertscripts
/app.ini中的模式调成Debug，查看/tmp文件夹下的日志文件也显示成功
![Snipaste_2022-07-28_22-05-32](https://user-images.githubusercontent.com/65064941/181525613-370aecef-2da6-4aaa-a299-ce73a12fc9ef.png)
查看zbxtable日志/usr/local/zbxtable/logs/app/logs/app.log有大量的提示
![Snipaste_2022-07-28_22-08-38](https://user-images.githubusercontent.com/65064941/181526041-c01f727b-2a2a-4833-ad75-21df3642c574.png)
然后前端界面上没有任何显示（ms-agent-1.0.3.tar.gz或者ms-agent-1.0.4.tar.gz都是一样的效果）
![Snipaste_2022-07-28_22-10-06](https://user-images.githubusercontent.com/65064941/181526351-4ce2ee8a-3b61-4572-b6fb-1f4430221779.png)
请问是我ms-agent的安装不对吗？或者配置有错误？我是卸载zbxtable1.0后安装2.0的，以前1.0版本没有这个问题。谢谢您的帮助

**Comment by canghai908** [comment]
zabbix版本多少，ms-agent的安装感觉有点问题，模板没有

**Comment by canghai908** [comment]
更新下2.1.0 怀疑是特殊字符处理问题

**Comment by linus-qintian** [comment]
好的老师，我去更新一下2.1.0，如果有问题再来请教。谢谢老师！

**Comment by canghai908** [comment]
好
