### ISSUE TITLE
怎么获取网卡和硬盘信息。

### ISSUE THREAD

**Issue by ripple0v0** [canghai908/zbxtable#47]
部署完成后，按照教程只能获取到CPU和内存信息。怎么获取到其他信息呢

**Comment by canghai908** [comment]
你的zabbix版本是多少？可能是zabbix版本问题

**Comment by ripple0v0** [comment]
Zabbix版本为：5.0.10

**Comment by canghai908** [comment]
主机用的模板是那个，是自己定义的还是系统默认的？

ripple ***@***.***> 于2022年8月22日周一 09:40写道：

**Comment by ripple0v0** [comment]
主机用的模版是自定义的

**Comment by canghai908** [comment]
自定义模板不支持，需要使用系统自带的模板
