### ISSUE TITLE
下载巡检表格乱码以及巡检内容是空的

### ISSUE THREAD

**Issue by 492083363** [canghai908/zbxtable#5]
测试用使用时，zbxtable1.0.5时，下载巡检报告，表格文件名时乱码，而且没有内容 
请问时需要更新升级嘛 
![image](https://user-images.githubusercontent.com/33111224/92252672-2308b380-ef01-11ea-9017-2e2fff813502.png)

![image](https://user-images.githubusercontent.com/33111224/92253028-a5917300-ef01-11ea-934b-b070b67bedf6.png)

**Comment by canghai908** [comment]
升级到最新，目前巡检只能到处linux和windows服务器的，交换机暂不支持。另外设备乱码是因为组名为中文，这个问题还需要看下。
