### ISSUE TITLE
升级到最新2.1后,启动后端报错,[E] [web.go:47]  strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by tyjin** [canghai908/zbxtable#55]
升级到最新2.1后,启动后端报错,[E] [web.go:47]  strconv.ParseInt: parsing "": invalid syntax
![image](https://user-images.githubusercontent.com/11436298/201618474-24222978-8906-4a92-9713-341beb3980f7.png)

**Comment by canghai908** [comment]
配置文件conf/app.conf末尾需要添加微信告警的对应配置，查看升级文档https://zbxtable.com/docs/install/update/
```
;wechat
wechat_agentid   = 1
wechat_corpid    = wxa7c63522727bxxxx
wechat_secret    = 7c63522727bxxxx
```
