### ISSUE TITLE
zbxtable.service failed

### ISSUE THREAD

**Issue by littleheart** [canghai908/zbxtable#6]
zbxtable.service failed. let me know what is the issue.

**Comment by canghai908** [comment]
Please provide zbxtable.log.

**Comment by pancq** [comment]
no log 

[root@zabbix conf]# systemctl status zbxtable
● zbxtable.service - zbxtable
   Loaded: loaded (/usr/lib/systemd/system/zbxtable.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 五 2020-11-13 16:35:16 CST; 3s ago
  Process: 16672 ExecStart=/bin/bash -c /usr/local/zbxtable/zbxtable web (code=exited, status=2)
 Main PID: 16672 (code=exited, status=2)

**Comment by canghai908** [comment]
@pancq  look the /var/log/messages，have some error。

**Comment by pancq** [comment]
@canghai908 数据库用户名和密码都没有错误
Nov 13 19:14:59 zabbix systemd: Started zbxtable.
Nov 13 19:15:00 zabbix bash: [ORM]2020/11/13 19:15:00 register db Ping `default`, Error 1045: Access denied for user 'zbxtable'@'::1' (using password: YES)
Nov 13 19:15:00 zabbix bash: must have one register DataBase alias named `default`
Nov 13 19:15:00 zabbix bash: goroutine 1 [running]:
Nov 13 19:15:00 zabbix bash: runtime/debug.Stack(0x36, 0x0, 0x0)
Nov 13 19:15:00 zabbix bash: /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
Nov 13 19:15:00 zabbix bash: runtime/debug.PrintStack()
Nov 13 19:15:00 zabbix bash: /usr/local/go/src/runtime/debug/stack.go:16 +0x22
Nov 13 19:15:00 zabbix bash: github.com/astaxie/beego/orm.bootStrap()
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/models_boot.go:302 +0x487
Nov 13 19:15:00 zabbix bash: github.com/astaxie/beego/orm.BootStrap()
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/models_boot.go:345 +0x8e
Nov 13 19:15:00 zabbix bash: github.com/astaxie/beego/orm.RunSyncdb(0xe77b97, 0x7, 0x100, 0x5, 0xc000208000)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/cmd.go:273 +0x26
Nov 13 19:15:00 zabbix bash: github.com/canghai908/zbxtable/models.ModelsInit()
Nov 13 19:15:00 zabbix bash: /var/lib/jenkins/workspace/zbxtable-rpm-centos7/models/base.go:41 +0x3cb
Nov 13 19:15:00 zabbix bash: github.com/canghai908/zbxtable/cmd.runWeb(0xc0001fcf20)
Nov 13 19:15:00 zabbix bash: /var/lib/jenkins/workspace/zbxtable-rpm-centos7/cmd/web.go:29 +0xa3
Nov 13 19:15:00 zabbix bash: github.com/urfave/cli.HandleAction(0xcfb6a0, 0xec2560, 0xc0001fcf20, 0xc0001fcf20, 0x0)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:528 +0x7c
Nov 13 19:15:00 zabbix bash: github.com/urfave/cli.Command.Run(0xe73706, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe81755, 0x10, 0x0, ...)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x57a
Nov 13 19:15:00 zabbix bash: github.com/urfave/cli.(*App).Run(0xc0000cda40, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x7c7
Nov 13 19:15:00 zabbix bash: main.main()
Nov 13 19:15:00 zabbix bash: /var/lib/jenkins/workspace/zbxtable-rpm-centos7/zbxtable.go:39 +0x16a
Nov 13 19:15:00 zabbix systemd: zbxtable.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 13 19:15:00 zabbix systemd: Unit zbxtable.service entered failed state.
Nov 13 19:15:00 zabbix systemd: zbxtable.service failed.
Nov 13 19:14:59 zabbix systemd: Started zbxtable.
Nov 13 19:15:00 zabbix bash: [ORM]2020/11/13 19:15:00 register db Ping `default`, Error 1045: Access denied for user 'zbxtable'@'::1' (using password: YES)
Nov 13 19:15:00 zabbix bash: must have one register DataBase alias named `default`
Nov 13 19:15:00 zabbix bash: goroutine 1 [running]:
Nov 13 19:15:00 zabbix bash: runtime/debug.Stack(0x36, 0x0, 0x0)
Nov 13 19:15:00 zabbix bash: /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
Nov 13 19:15:00 zabbix bash: runtime/debug.PrintStack()
Nov 13 19:15:00 zabbix bash: /usr/local/go/src/runtime/debug/stack.go:16 +0x22
Nov 13 19:15:00 zabbix bash: github.com/astaxie/beego/orm.bootStrap()
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/models_boot.go:302 +0x487
Nov 13 19:15:00 zabbix bash: github.com/astaxie/beego/orm.BootStrap()
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/models_boot.go:345 +0x8e
Nov 13 19:15:00 zabbix bash: github.com/astaxie/beego/orm.RunSyncdb(0xe77b97, 0x7, 0x100, 0x5, 0xc000208000)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/cmd.go:273 +0x26
Nov 13 19:15:00 zabbix bash: github.com/canghai908/zbxtable/models.ModelsInit()
Nov 13 19:15:00 zabbix bash: /var/lib/jenkins/workspace/zbxtable-rpm-centos7/models/base.go:41 +0x3cb
Nov 13 19:15:00 zabbix bash: github.com/canghai908/zbxtable/cmd.runWeb(0xc0001fcf20)
Nov 13 19:15:00 zabbix bash: /var/lib/jenkins/workspace/zbxtable-rpm-centos7/cmd/web.go:29 +0xa3
Nov 13 19:15:00 zabbix bash: github.com/urfave/cli.HandleAction(0xcfb6a0, 0xec2560, 0xc0001fcf20, 0xc0001fcf20, 0x0)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:528 +0x7c
Nov 13 19:15:00 zabbix bash: github.com/urfave/cli.Command.Run(0xe73706, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe81755, 0x10, 0x0, ...)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x57a
Nov 13 19:15:00 zabbix bash: github.com/urfave/cli.(*App).Run(0xc0000cda40, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
Nov 13 19:15:00 zabbix bash: /home/mygo/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x7c7
Nov 13 19:15:00 zabbix bash: main.main()
Nov 13 19:15:00 zabbix bash: /var/lib/jenkins/workspace/zbxtable-rpm-centos7/zbxtable.go:39 +0x16a
Nov 13 19:15:00 zabbix systemd: zbxtable.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 13 19:15:00 zabbix systemd: Unit zbxtable.service entered failed state.
Nov 13 19:15:00 zabbix systemd: zbxtable.service failed.

**Comment by canghai908** [comment]
问题很显然，Nov 13 19:15:00 zabbix bash: [ORM]2020/11/13 19:15:00 register db Ping default, Error 1045: Access denied for user 'zbxtable'@'::1' (using password: YES)  这里配置的 数据库帐号密码有问题，帐号授权必须按照文档里的授权操作。
