### ISSUE TITLE
遇到一个新问题

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#62]
之前因为各主机没有进行分组 ，所以在初始化的时候esxi和window主机全部添加进来了。（如图）
![image](https://user-images.githubusercontent.com/99636954/209785597-fbed29e6-845c-457b-807a-a9248339dc1c.png)
我现在对window和esxi进行重新分组并且进行初始化  但是esxi还是在window主机的这个组里面 我想问下如何去除？还是我遇到bug了
![image](https://user-images.githubusercontent.com/99636954/209785921-1a25bb96-14b6-41d1-8730-672357083d76.png)

**Comment by Hi-360** [comment]
![image](https://user-images.githubusercontent.com/99636954/209786241-11a0d75b-089b-4173-ad5a-c40c528b305b.png)

**Comment by canghai908** [comment]
主机资产里，Type字段里清理，保存 即可

**Comment by fengbo1029** [comment]
![image](https://user-images.githubusercontent.com/99636954/227082028-45818c19-2c3e-4cec-8e8f-ca8ab31bdb55.png)
张总是这里面吗？本人技术比较菜

**Comment by Hi-360** [comment]
![image](https://user-images.githubusercontent.com/99636954/227082391-b6d8ee3d-6770-4b56-8ffa-ccc2bb8d7802.png)
张总是这个里面？我没找到  我技术很菜

**Comment by canghai908** [comment]
![image](https://user-images.githubusercontent.com/1450994/227083069-2bb39263-7b95-4811-8e0c-b187f8ba94fe.png)
删除HW_SRV 保存即可，等待5分钟左右就会更新

**Comment by Hi-360** [comment]
可以了 张总  感谢
