### ISSUE TITLE
zbxtable 启动时报错，查看配置文件都是正常

### ISSUE THREAD

**Issue by xinanll** [canghai908/zbxtable#64]
![image](https://user-images.githubusercontent.com/32351216/210351894-536b6126-088d-413f-8b4d-79892171521e.png)
2023/01/03 19:46:50.031 [E] [web.go:47]  invalid character '<' looking for beginning of value

**Comment by canghai908** [comment]
zabbix的web地址填写错误，确定那个地址能打开zabbix
