### ISSUE TITLE
zbxtable 发送的告警状态全是恢复

### ISSUE THREAD

**Issue by CCczya** [canghai908/zbxtable#66]
debug日志：  "msg": "readObjectStart: expect { or n, but found \ufffd, error found in #1 byte of ...|【故障\ufffd\ufffd|..., bigger context ...|【故障信息】Zabbix agent on DESKTOP-K8T5K2H:1|..."

**Comment by CCczya** [comment]
[E] [before.go:160]  readObjectStart: expect { or n, but found �, error found in #1 byte of ...|【故障�|..., bigger context ...|【故障信息】【ZABBIX】客户端断开连接|...

**Comment by CCczya** [comment]
![image](https://user-images.githubusercontent.com/84966725/220802031-5a43a5fd-2f33-41e9-89ea-2678001bfa20.png)
Zabbix上刚出现的告警还没恢复，告警发送到zbxtable上告警状态全是恢复

**Comment by canghai908** [comment]
这是告警解析问题，使用最新版本的2.1.1，
```
./zbxtable uninstall
```
卸载后，再安装一次试试
```
./zbxtable install
```
