### ISSUE TITLE
docker安装zabbix告警通知无法发送到zbxtable

### ISSUE THREAD

**Issue by yuesans** [canghai908/zbxtable#68]
zabbix: 使用docker安装， 版本为 6.2.6
ip:192.168.40.125
mysql版本为8.0
dockers容器如下：
[root@localhost alertscripts]# docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED        STATUS             PORTS                                                  NAMES
d4c250df13a3   zabbix/zabbix-web-nginx-mysql:latest   "docker-entrypoint.sh"   2 months ago   Up About an hour   8443/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp        zabbix-web-nginx-mysql
b9218a0456cc   zabbix/zabbix-agent:latest             "/sbin/tini -- /usr/…"   2 months ago   Up About an hour   0.0.0.0:10050->10050/tcp, :::10050->10050/tcp          zabbix-agent
8e4a4cbbaff1   zabbix/zabbix-server-mysql:latest      "/sbin/tini -- /usr/…"   2 months ago   Up About an hour   0.0.0.0:10051->10051/tcp, :::10051->10051/tcp          zabbix-server-mysql
9c5411778b8b   zabbix/zabbix-java-gateway:latest      "docker-entrypoint.s…"   2 months ago   Up About an hour   10052/tcp                                              zabbix-java-gateway
e72958156645   mysql:8.0                              "docker-entrypoint.s…"   2 months ago   Up About an hour   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   mysql-server

zbxtable配置在另一个主机上192.168.40.30上，端口为8888，访问正常，
zbxtable为官网安装方式，安装和初始化无报错，token为安装包原始token
nginx和redis为yum安装
安装参考的官网，使用的相同安装包：https://zbxtable.com/docs/install/install/
 
zabbix-server安装ms-agent，
1，将容器目录/usr/lib/zabbix/alertscripts映射到本地/usr/lib/zabbix/alertscripts目录
2，下载ms-agent :wget https://dl.cactifans.com/zbxtable/ms-agent-1.0.4.tar.gz
tar -xzf ms-agent-1.0.4.tar.gz
修改配置 vi /ms-agent-1.0.4/app.ini
mv ms-agent-1.0.4 /usr/lib/zabbix/alertscripts/ms-agent
chmod a+x /usr/lib/zabbix/alertscripts/ms-agent/*
测试看，zabbix-server动态日志会报错：sh: /usr/lib/zabbix/alertscripts/ms-agent: Permission denied，zbxtable查看告警一直为空
尝试解决方案1：然后修改属主和属主为zabbix，添加权限，依然报相同错误
尝试解决方案2：只将执行文件复制到对应目录
wget https://dl.cactifans.com/zbxtable/ms-agent-1.0.4.tar.gz
tar -xzf ms-agent-1.0.4.tar.gz
修改配置 vi /ms-agent-1.0.4/app.ini
mv ms-agent-1.0.4/ms-agent /usr/lib/zabbix/alertscripts/
chmod a+x /usr/lib/zabbix/alertscripts/ms-agent
容器内执行：mkdir /etc/ms-agent && mv ms-agent-1.0.4/app.ini /etc/ms-agent/
测试看zabbix动态日志报错：sh: /usr/lib/zabbix/alertscripts/ms-agent: not found
zbxtable查看告警一直为空

截图如下：
![1678359154677](https://user-images.githubusercontent.com/127397258/224007243-17daa729-4061-4865-ad0e-d9078b4540d3.png)

**Comment by yuesans** [comment]
![image](https://user-images.githubusercontent.com/127397258/224007800-43f6eefd-d551-4c7a-909a-a2884b063ef5.png)

**Comment by canghai908** [comment]
ms-agent容器跑需要使用centos或ubuntu镜像，不能使用alpine精简镜像，目前已修复。

**Comment by yuesans** [comment]
大佬您当天已帮忙远程看了，已解决，忘登录更新问题了，多谢
