### ISSUE TITLE
zbxtable 安装配置 Ms-Agent报错

### ISSUE THREAD

**Issue by MaoAnmi** [canghai908/zbxtable#70]
系统环境：CentOS7.9
zabbix 6.4
mysql 8.0.31

[root@zabbix ~]# cd /usr/local/zbxtable/
[root@zabbix zbxtable]# ./zbxtable install
2023/03/12 17:25:52.782 [I] [command.go:173]  Create media type successfully!
2023/03/12 17:25:53.943 [I] [command.go:173]  Create user group successfully!
2023/03/12 17:25:54.336 [E] [command.go:173]  -32602 (Invalid params.): Invalid parameter "/1": unexpected parameter "alias".
[root@zabbix zbxtable]# ll

**Comment by canghai908** [comment]
请使用最新的2.1.1版本，已支持zabbix 6.4版本

**Comment by MaoAnmi** [comment]
已解决，谢谢，期待更好的产品
