### ISSUE TITLE
升级操作文档发现一处错误

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#73]
![image](https://user-images.githubusercontent.com/99636954/227075393-a395cba4-2f99-44b0-bb33-220d3d036130.png)

**Comment by canghai908** [comment]
多谢，已更新。

**Comment by fengbo1029** [comment]
![image](https://user-images.githubusercontent.com/99636954/227077467-7092e75d-4bc2-4fdb-85ac-24dd89dd76d6.png)
![Uploading image.png…]()
张总web页面显示还是2.1 我这个是升级成功了吧？

**Comment by Hi-360** [comment]
![image](https://user-images.githubusercontent.com/99636954/227077950-f7447c38-97ee-4abb-848b-6845f81ceb1f.png)
![image](https://user-images.githubusercontent.com/99636954/227077991-c1611ed5-09de-4dec-b535-8734c6d28d4f.png)
![image](https://user-images.githubusercontent.com/99636954/227078025-05dc808e-40af-4ffd-8c67-af0e2ed5f6a1.png)
张总我这个是升级成功了吗？我看web端显示还是2.1 不是2.1.1

**Comment by canghai908** [comment]
升级ok了，前端不变

**Comment by Hi-360** [comment]
![image](https://user-images.githubusercontent.com/99636954/227110829-bbad0a08-99d7-43b3-8f94-23b169044f25.png)
张总这个告警  三个运算符我不明白是什么意思？还有就是 值：   那边填写的是主机的名称？还是主机可见名称？

**Comment by canghai908** [comment]
试试就知道了
