### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by PedroRocha79** [canghai908/zbxtable#74]
![image](https://user-images.githubusercontent.com/102227374/231025136-f759ee38-a005-4ab0-af26-ad59bd0f19c8.png)
![image](https://user-images.githubusercontent.com/102227374/231025187-2ee0373e-d741-4b5a-9325-15af55bf9182.png)

**Comment by canghai908** [comment]
Please provide information such as zabbix version and zbxtable version
