### ISSUE TITLE
zbxtable使用遇到点问题

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#77]
![7f29506b5aa2f4eb8f1f5c5a9049e3e](https://github.com/canghai908/zbxtable/assets/99636954/554e481a-db98-4a16-9129-38b5e778c740)
  就是告警统计里面，字体前面部分都遮挡住了， 显示不全。

**Comment by canghai908** [comment]
木有前端工程师支持，本人前端不太好，目前没办法修复，后续看情况。

**Comment by Hi-360** [comment]
好的  大佬最近zbxtable会有新功能更新吗？
