### ISSUE TITLE
Linux系统内核版本不显示

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#81]
你好楼主，我想问下这个内核版本为啥不显示？前面监控的Linux系统 内核都能正常显示的
![image](https://github.com/canghai908/zbxtable/assets/99636954/7710b611-11bb-42f2-b158-002974d41c10)

**Comment by canghai908** [comment]
查看采集指标system.uname是否已经采集

**Comment by Hi-360** [comment]
问题已经解决

**Comment by canghai908** [comment]
ok
