### ISSUE TITLE
能否增加系统巡检报表功能？

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#82]
你好  一直在使用zbxtable，使用体验非常好。特别是网络报表功能 、希望能增加一个系统自动化巡检的报表的功能 可以通过邮件的方式发送到指定的管理员   包含win和Linux的  我现在虚拟化使用的是vmware的自动化巡检 报表如下
![image](https://github.com/canghai908/zbxtable/assets/99636954/8c084409-a06f-4a5b-9b7e-735200f1c47d)

**Comment by canghai908** [comment]
你这个里面的数据是 瞬时的数据还是平均？

**Comment by Hi-360** [comment]
> 你这个里面的数据是 瞬时的数据还是平均？
平均数据哈

**Comment by canghai908** [comment]
> > 你这个里面的数据是 瞬时的数据还是平均？
> > 平均数据哈

平均就是 一周或者一个月的平均数，瞬时就是 巡检时刻机器的实时数据

**Comment by Hi-360** [comment]
明白  希望增加我提的这个功能 ，应该是多数人想要的功能
