### ISSUE TITLE
wechat微信配置问题

### ISSUE THREAD

**Issue by BananaRR** [canghai908/zbxtable#83]
我已经安装教程说的配置了企业微信。app.ini文件也配置了相关企业微信的信息
但是报警没有发送。并且告警分发里面配置的其他非默认规则。ZBXtable不会发生发送动作？是需要怎么配置吗？
有大佬可以详细说下吗?

**Comment by BananaRR** [comment]
事件ID: 104400044`, `WorkwxClientError { Code: 81013, Msg: "user & party & tag all invalid, hint: [1698649970565140354337866], from ip: 220.173.103.187, more info at https://open.work.weixin.qq.com/devtool/query?e=81013" }`, `1`

**Comment by BananaRR** [comment]
![image](https://github.com/canghai908/zbxtable/assets/33884722/8f9a5ab1-e6cc-40df-ab99-b6c2b2e89379)
是不是哪里配置错误。这里和demo里面配置的有区别

**Comment by BananaRR** [comment]
> 事件ID: 104400044`, `WorkwxClientError { Code: 81013, Msg: "user & party & tag all invalid, hint: [1698649970565140354337866], from ip: 220.173.103.187, more info at https://open.work.weixin.qq.com/devtool/query?e=81013" }`, `1`

可以在下个版本中增加一个部门ID和标签ID的发送选项吗

**Comment by BananaRR** [comment]
> 事件ID: 104400044`, `WorkwxClientError { Code: 81013, Msg: "user & party & tag all invalid, hint: [1698649970565140354337866], from ip: 220.173.103.187, more info at https://open.work.weixin.qq.com/devtool/query?e=81013" }`, `1`

可以在下个版本中增加一个部门ID和标签ID的发送选项吗

**Comment by canghai908** [comment]
> 事件ID: 104400044`, `WorkwxClientError { Code: 81013, Msg: "user & party & tag all invalid, hint: [1698649970565140354337866], from ip: 220.173.103.187, more info at https://open.work.weixin.qq.com/devtool/query?e=81013" }`, `1`
这个错误是企业微信的用户id错误，确保用户的账号是企业微信里的账号，不一定是微信号。
![image](https://github.com/canghai908/zbxtable/assets/1450994/9854d519-7561-40b0-bf24-4d66ab95c89c)

**Comment by BananaRR** [comment]
通过复制账号直接复制的 例如图片，但是发送仍然还是失败。不知道什么原因，另外。我新建的规则没有发生触发报警的动作,只有默认规则由触发了报警动作




&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月31日(星期二) 下午3:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [canghai908/zbxtable] wechat微信配置问题 (Issue #83)





  
事件ID: 104400044, WorkwxClientError { Code: 81013, Msg: "user &amp; party &amp; tag all invalid, hint: [1698649970565140354337866], from ip: 220.173.103.187, more info at https://open.work.weixin.qq.com/devtool/query?e=81013" }, 1`
 这个错误是企业微信的用户id错误，确保用户的账号是企业微信里的账号，不一定是微信号。

**Comment by canghai908** [comment]
告警规则里 没有租户，所以没成功。租户在ms-agent配置文件里配置

**Comment by BananaRR** [comment]
ms-agent里面的配置有租户，但是没有生效
![image](https://github.com/canghai908/zbxtable/assets/33884722/6f12ce05-2917-4efe-b4cb-118df9dfceb6)

![image](https://github.com/canghai908/zbxtable/assets/33884722/026198e4-8f87-4efd-9abd-9b6bcf0ccc5e)
![image](https://github.com/canghai908/zbxtable/assets/33884722/89b9593b-c893-4246-98a5-649cfd6e2222)

**Comment by canghai908** [comment]
> ms-agent里面的配置有租户，但是没有生效 ![image](https://user-images.githubusercontent.com/33884722/279305211-6f12ce05-2917-4efe-b4cb-118df9dfceb6.png)
> 
> ![image](https://user-images.githubusercontent.com/33884722/279304690-026198e4-8f87-4efd-9abd-9b6bcf0ccc5e.png) ![image](https://user-images.githubusercontent.com/33884722/279304731-89b9593b-c893-4246-98a5-649cfd6e2222.png)

看了代码，发动这个就是从数据库获取微信账号发送，建议把其他规则也配置成admin的微信账号测试下，确定下微信账号是否正确。

**Comment by BananaRR** [comment]
![image](https://github.com/canghai908/zbxtable/assets/33884722/f08d9ca0-d813-406d-ab81-e369dea97594)
测试admin的默认规则发送企业微信是正常的，
我在数据库里面测试。配置m_type下的其他规则改成2以后。发送都是正常的。如果新增的两条规则都是配置m_type 为2 那么只有第一条规则会发送信息。其他的不会发送信息。
m_type 新增的是1的状态。发送报警里面不会看到触发发送报警的记录, 这是什么情况？需要注意哪里要配置吗

**Comment by canghai908** [comment]
> ![image](https://user-images.githubusercontent.com/33884722/279568618-f08d9ca0-d813-406d-ab81-e369dea97594.png) 测试admin的默认规则发送企业微信是正常的， 我在数据库里面测试。配置m_type下的其他规则改成2以后。发送都是正常的。如果新增的两条规则都是配置m_type 为2 那么只有第一条规则会发送信息。其他的不会发送信息。 m_type 新增的是1的状态。发送报警里面不会看到触发发送报警的记录, 这是什么情况？需要注意哪里要配置吗

m_type 为默认规则，rule不符合才会走默认规则，你这个情况大概率是rule规则问题，检查rule规则。

**Comment by BananaRR** [comment]
![image](https://github.com/canghai908/zbxtable/assets/33884722/b61bd7da-74d8-4739-8943-02a14514a5c7)
![image](https://github.com/canghai908/zbxtable/assets/33884722/dbe5ac65-2fc3-47ce-9cca-c1eac260851e)

应该是您说的rule的问题。。
目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?

**Comment by BananaRR** [comment]
> ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> 
> 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?



> ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> 
> 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?

![image](https://github.com/canghai908/zbxtable/assets/33884722/80943cd9-0f02-4451-911d-f89f94d2a114)

**Comment by canghai908** [comment]
> > ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> > 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?
> 
> > ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> > 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?
> 
> ![image](https://user-images.githubusercontent.com/33884722/279928725-80943cd9-0f02-4451-911d-f89f94d2a114.png)
你这显然有问题啊，你把默认的规则禁用了。而下面的规则里都是等于空，又匹配不了，那可不就是什么都不做吗
![image](https://github.com/canghai908/zbxtable/assets/1450994/726a45cb-7d10-4bca-971a-748a1889a4f1)
这都是空，都匹配不上

**Comment by BananaRR** [comment]
> > > ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> > > 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> > > 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/33884722/279928725-80943cd9-0f02-4451-911d-f89f94d2a114.png)
> > 你这显然有问题啊，你把默认的规则禁用了。而下面的规则里都是等于空，又匹配不了，那可不就是什么都不做吗
> > ![image](https://user-images.githubusercontent.com/1450994/280160850-726a45cb-7d10-4bca-971a-748a1889a4f1.png)
> > 这都是空，都匹配不上
大佬你好。确实是rule的问题。目前发现只能做一条规则。如果rule里面我增量了两个条件就不会发送了。一个条件发送正常
![image](https://github.com/canghai908/zbxtable/assets/33884722/94c973a2-1e62-40bf-96df-67bb7d886a5a)

**Comment by BananaRR** [comment]
> > > ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> > > 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/33884722/279926591-b61bd7da-74d8-4739-8943-02a14514a5c7.png) ![image](https://user-images.githubusercontent.com/33884722/279926826-dbe5ac65-2fc3-47ce-9cca-c1eac260851e.png)
> > > 应该是您说的rule的问题。。 目前我是禁用默认策略,查看日志是提示rule 是空的。是否是我再搭建过程有问题了?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/33884722/279928725-80943cd9-0f02-4451-911d-f89f94d2a114.png)
> > 你这显然有问题啊，你把默认的规则禁用了。而下面的规则里都是等于空，又匹配不了，那可不就是什么都不做吗
> > ![image](https://user-images.githubusercontent.com/1450994/280160850-726a45cb-7d10-4bca-971a-748a1889a4f1.png)
> > 这都是空，都匹配不上

确实是rule的问题。感谢
