### ISSUE TITLE
command  ./zbxtable install error 

### ISSUE THREAD

**Issue by zcrdhm** [canghai908/zbxtable#84]
2023/12/08 10:56:30.459 [I] [command.go:173]  Create media type successfully!
2023/12/08 10:56:30.500 [I] [command.go:173]  Create user group successfully!
2023/12/08 10:56:30.549 [E] [command.go:173]  -32602 (Invalid params.): Invalid parameter "/1": unexpected parameter "alias".

zabbix-server    6.4.8
CentOS Linux release 7.9.2009

**Comment by canghai908** [comment]
what version is your zbxtable version

**Comment by zcrdhm** [comment]
CopyrightZbxTable 2.1.0

**Comment by canghai908** [comment]
执行./zbxtable --version 查看具体版本
```
[root@10-23-68-220 zbxtable]# ./zbxtable --version
ZbxTable Version:=2.1.1
Git Commit Hash:=73448128bfbe5ed477af6af921c0870b612b9fae
UTC Build Time:=2023-03-22_09:37:44AM
```
如果不是2.1.1版本建议升级到2.1.1版本
