### ISSUE TITLE
搭建好之后卡在输入账密界面

### ISSUE THREAD

**Issue by liuzhen225588** [canghai908/zbxtable#85]
老哥，2.0是不是出bug了。我搭建好之后去输入账号密码登录跳转不到主界面，环境啥的都正常
![20231211-210021](https://github.com/canghai908/zbxtable/assets/54694256/46ec0252-e962-47f5-8bd9-aaa05b75846b)

**Comment by canghai908** [comment]
搭建好之后，先确保后台启动再说，进不去是后台没有启动。
![image](https://github.com/canghai908/zbxtable/assets/1450994/3180e46a-860f-44a3-90f3-0d4439d7282b)
