### ISSUE TITLE
zbxtable install error 

### ISSUE THREAD

**Issue by degni20** [canghai908/zbxtable#86]
[root@zabbixbi201 zbxtable]# ./zbxtable install
2023/12/13 13:56:02.235 [I] [proc.go:250]  Currently version 2.1.1
2023/12/13 13:56:02.280 [I] [proc.go:250]  Next run, I should be 2.1.1
2023/12/13 13:56:02.333 [I] [command.go:273]  Create media type successfully!
2023/12/13 13:56:02.348 [I] [command.go:273]  Create user group successfully!
2023/12/13 13:56:02.366 [E] [command.go:273]  -32602 (Invalid params.): Incorrect value for field "/1/passwd": must contain at least one digit.
[root@zabbixbi201 zbxtable]# ./zbxtable --version
2023/12/13 13:57:39.403 [I] [proc.go:250]  Currently version 2.1.1
2023/12/13 13:57:39.490 [I] [proc.go:250]  Next run, I should be 2.1.1
ZbxTable Version:=2.1.1
Git Commit Hash:=73448128bfbe5ed477af6af921c0870b612b9fae
UTC Build Time:=2023-03-22_09:37:44AM

zabbix_server version:6.4.9

**Comment by canghai908** [comment]
must contain at least one digit.
![image](https://github.com/canghai908/zbxtable/assets/1450994/e8c85a00-0fa8-43ce-ba5b-538095c7ed63)

**Comment by degni20** [comment]
您好，来信已收到；如有需要我会稍后回复，谢谢！
