### ISSUE TITLE
告警问题咨询

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#87]
张总这个分发维度   有问题请教，现在的需求就是当erp-url这个组里面    监控项出现告警  并且级别为严重  然后给对应的负责人发送对应的邮件。我想问下如何让设置？
我之前配置了 但是告警级别为警告的时候也给对应的负责人发送邮件，不明白里面的内容该如何配置   

![image](https://github.com/canghai908/zbxtable/assets/99636954/9a034f9e-61d4-4843-bd8f-ab0f5354499c)
![image](https://github.com/canghai908/zbxtable/assets/99636954/84a71679-1acd-42a1-a9c7-46a26503bc06)

**Comment by canghai908** [comment]
主机组==网站URL
告警级别==4
 即可
告警级别对对应数字
https://www.zabbix.com/documentation/6.0/en/manual/api/reference/trigger/object
```
0 - (default) not classified;
1 - information;
2 - warning;
3 - average;
4 - high;
5 - disaster.
```

**Comment by Hi-360** [comment]
> 主机组==网站URL 同等等级==4 即可 相当级别对对应数字 https://www.zabbix.com/documentation/6.0/en/manual/api/reference/trigger/object
> 
> ```
> 0 - (default) not classified;
> 1 - information;
> 2 - warning;
> 3 - average;
> 4 - high;
> 5 - disaster.
> ```
感谢张总
张总这个自定义logo 如何配置啊？
![image](https://github.com/canghai908/zbxtable/assets/99636954/537990aa-71f1-4795-9051-fb6212fad75a)

**Comment by canghai908** [comment]
这2个文件里
```
template/mail_problem.tpl 
template/mail_recovery.tpl
```
修改
```
<img src="https://dl.cactifans.com/assets/LogoSample.png" alt="" style="width: 256px; height: 67px;"/>
```
2个文件里自行修改

**Comment by Hi-360** [comment]
张总我以前监控主机的时候是采用被动的方式，今天我把被动切换成主动了   遇到了一个问题     就是zbxtable里面的时间不准确啦，我想问下这个是什么原因导致的？
![image](https://github.com/canghai908/zbxtable/assets/99636954/d2083c2a-541b-425b-ab91-66c0463bc289)
这个时间一直不动

**Comment by canghai908** [comment]
> 张总我以前监控主机的时候是采用被动的方式，今天我把被动切换成主动了 遇到了一个问题 就是zbxtable里面的时间不准确啦，我想问下这个是什么原因导致的？ ![image](https://private-user-images.githubusercontent.com/99636954/293144207-d2083c2a-541b-425b-ab91-66c0463bc289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjgzODcsIm5iZiI6MTcwMzc2ODA4NywicGF0aCI6Ii85OTYzNjk1NC8yOTMxNDQyMDctZDIwODNjMmEtNTQxYi00MjViLWFiOTEtNjZjMDQ2M2JjMjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEyNTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOGUyOWFhYmMxNjRkNTA3M2IyNTY0MTlhNjNhOWU5NDYzY2Q1YjYwMjZjZjgwOGY0NDJhMzBjMzNhNTkzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vM0bgZiIGJKld9DRb8SInyhi1e3kP5ITrxyd6Z2m9d4) 这个时间一直不动

不太清楚，指标更新这个就更行。

**Comment by Hi-360** [comment]
> > 张总我以前监控主机的时候是采用被动的方式，今天我把被动切换变成主动了遇到一个问题就是zbxtable里面的时间不准确啦，我想问下这个是什么原因导致的？![图像](https://private-user-images.githubusercontent.com/99636954/293144207-d2083c2a-541b-425b-ab91-66c0463bc289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjgzODcsIm5iZiI6MTcwMzc2ODA4NywicGF0aCI6Ii85OTYzNjk1NC8yOTMxNDQyMDctZDIwODNjMmEtNTQxYi00MjViLWFiOTEtNjZjMDQ2M2JjMjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEyNTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOGUyOWFhYmMxNjRkNTA3M2IyNTY0MTlhNjNhOWU5NDYzY2Q1YjYwMjZjZjgwOGY0NDJhMzBjMzNhNTkzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vM0bgZiIGJKld9DRb8SInyhi1e3kP5ITrxyd6Z2m9d4)这段时间一直不动
> 
> 还不太清楚，指标更新这个就更行了。

我刚才尝试把主动模式改为被动模式  现在zbxtable里面展示的时间准确了

**Comment by Hi-360** [comment]
张总主动模式 时间展示的问题  是不是zbxtable存在的bug

**Comment by canghai908** [comment]
没见过你说的这种情况。这个是绑定Item的，item数据更新这个就更新。本人亲测米有问题，多找自己问题，关闭此问题了
![image](https://github.com/canghai908/zbxtable/assets/1450994/30dd140f-7244-4b50-ac1e-f3df4d634675)
![image](https://github.com/canghai908/zbxtable/assets/1450994/e87c91fb-07f9-4984-b468-3c499364238f)
![image](https://github.com/canghai908/zbxtable/assets/1450994/f5ea20dc-f2d8-446f-83de-6125b04532ef)
![image](https://github.com/canghai908/zbxtable/assets/1450994/412cf6a2-2603-47e9-b3c9-cff8baed4588)
