### ISSUE TITLE
使用你的分区表配置出现点问题

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#88]
张总你好 
 我按照你博客 教程上面对zabbix 数据库进行分区 ，遇到点问题。（https://blog.cactifans.com/2018/02/25/zabbix3.4%E5%88%86%E5%8C%BA%E8%A1%A8%E9%85%8D%E7%BD%AE/）
![image](https://github.com/canghai908/zbxtable/assets/99636954/96b26403-ab8c-4ac6-b7aa-e63ea6dd679c)

我查询了有三个 zabbix server这个文件 我想问下调用的是哪一个啊？对了   按照这个教程执行过以后  zabbix web无法进行登录了 
![image](https://github.com/canghai908/zbxtable/assets/99636954/852415d5-daba-41af-8c5e-8f0374da658f)

![image](https://github.com/canghai908/zbxtable/assets/99636954/8fb540c4-c59a-4f7c-b61d-f73682ee63b9)

**Comment by canghai908** [comment]
你没看到吗？
![image](https://github.com/canghai908/zbxtable/assets/1450994/32dbc85d-32d1-4a8c-8a3a-cca76f940d2f)
zabbix 2.0版本才需要你这里应该是选n，你选错了，另外后面这个web数据库连接不上和分区没关系，自行检查数据库连接参数及权限。

**Comment by Hi-360** [comment]
> 你没看到吗？ zabbix 2.0版本才需要你这里应该是选n，你选错了，另外后面这个web数据库连接不上和分区没关系，自行检查数据库连接参数及权限。 ![图像](https://private-user-images.githubusercontent.com/1450994/292800362-32dbc85d-32d1-4a8c-8a3a-cca76f940d2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjI4OTQsIm5iZiI6MTcwMzU2MjU5NCwicGF0aCI6Ii8xNDUwOTk0LzI5MjgwMDM2Mi0zMmRiYzg1ZC0zMmQxLTRhOGMtOGEzYS1jY2E3NmY5NDBkMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDM0OTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM0YTQ5YWY0MTk3NTJiZGQzYzUwN2YzMDI1MDg0MDFmMWE3NDIyNzM3ZWIxNDA0NzkyMTRkODA5ZGUxZmMxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vjRbQ4CgPr5mFPdf7_oiCLVmlcmvJC44TTMNTl3e8nA)

这个就
![0B587985804647AE0B990319D11E3F04](https://github.com/canghai908/zbxtable/assets/99636954/abc09aa5-212c-4c7b-ac5f-3a4764ffd360)

**Comment by fengbo1029** [comment]
> 你没看到吗？ ![image](https://private-user-images.githubusercontent.com/1450994/292800362-32dbc85d-32d1-4a8c-8a3a-cca76f940d2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjMwMDMsIm5iZiI6MTcwMzU2MjcwMywicGF0aCI6Ii8xNDUwOTk0LzI5MjgwMDM2Mi0zMmRiYzg1ZC0zMmQxLTRhOGMtOGEzYS1jY2E3NmY5NDBkMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDM1MTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRlOWNjYjIxMzA5ZWIxZTc3ZmFkNzViNDRlZWU4YmZjMGE2MmZiMTYwODEzNTJmNDE4NDBkOWQyNWNhMmJiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lnjHmv_GE1N57ShpYRiVTwjU_3Gv1VXLjoXF9Q39OiQ) zabbix 2.0版本才需要你这里应该是选n，你选错了，另外后面这个web数据库连接不上和分区没关系，自行检查数据库连接参数及权限。

但是没执行这个脚本之前  登录到zabbix web端是正常   执行后就不行了  我来检查下

**Comment by Hi-360** [comment]
问题找到了  张总    感谢了    张总年前会安排zbxtable进行吗？

**Comment by canghai908** [comment]
不会更新，年后再说
