### ISSUE TITLE
zbxtable系统报表里面能否增加一个硬盘容量显示栏目

### ISSUE THREAD

**Issue by Hi-360** [canghai908/zbxtable#89]
![image](https://github.com/canghai908/zbxtable/assets/99636954/a2ed2c5a-bcb8-4988-abc4-b22d0ee0ce3b)
张总这个报表里面能否增加一个 硬盘的使用情况栏目？

**Comment by canghai908** [comment]
不好整，硬盘数量不固定，数据获取逻辑不一样
