### ISSUE TITLE
脚本运行错误

### ISSUE THREAD

**Issue by handsome12y** [canghai908/zbxtable#9]
2020/11/16 11:54:58.906 [I] [install.go:45]  Zabbix Admin User: Admin 
2020/11/16 11:54:58.906 [I] [install.go:46]  Zabbix Admin Password: zabbix 
2020/11/16 11:54:59.066 [I] [install.go:53]  登录zabbix平台成功! 
2020/11/16 11:54:59.117 [I] [install.go:59]  zabbix版本为: 5.2.0 
2020/11/16 11:54:59.210 [I] [install.go:103]  创建告警媒介成功! 
2020/11/16 11:54:59.294 [I] [install.go:116]  创建告警用户组成功! 
2020/11/16 11:54:59.401 [E] [install.go:141]  -32602 (Invalid params.): Invalid parameter "/1": unexpected parameter "type".

**Comment by canghai908** [comment]
5.2版本api有变化，升级到1.0.8版本即可解决。
