### ISSUE TITLE
启动Zbxtable服务失败

### ISSUE THREAD

**Issue by VictorLeeNian** [canghai908/zbxtable#90]
服务启动的时候报错，查看日志提示无效语法。日志如图
![日志](https://github.com/canghai908/zbxtable/assets/133093256/c4c65554-9558-4692-9aac-ea7c4368017b)

**Comment by canghai908** [comment]
配置文件配置问题，配置文件里
```
; wechat
wechat_agentid   = 1
wechat_corpid    = wxa7c63522727b7790
wechat_secret    = 5HA0o9bkvMMFDp8yFswwZIifoSDtmCJ4k
```
wechat_agentid配置为空导致
