### ISSUE TITLE
Zabbix分组问题请教

### ISSUE THREAD

**Issue by baalchina** [canghai908/zbxtable#95]
请教您一个zbxtable的问题，我们的zabbix是按照业务类型分的主机组，例如OA组、数据库组、网站组，每个组里有win，也有lin。看了您的视频，我在编辑映射的时候在对应操作系统下面得选择主机组，这个怎么选择呢？

是不是我得到zabbix里重新新建Linux、Windows组，然后在把对应系统的主机放进去？例如oa的windows，那就同时放在oa主机组和linux主机组？接下来在到zbxtable选择linux组？

谢谢！

**Comment by canghai908** [comment]
目前是按照主机组分的所以你需要

>zabbix里重新新建Linux、Windows组，然后在把对应系统的主机放进去。例如oa的windows，那就同时放在oa主机组和linux主机组.接下来在到zbxtable选择linux组

一个主机可以属于多个主机组，所以把机器加到另外的主机组不会影响其他。

**Comment by baalchina** [comment]
感谢测试了一下，单独建了个给zbxtable用的组，可以生效。谢谢！
